config.load_autoconfig()
c.auto_save.session = True
c.colors.downloads.start.bg = '#005D82'
c.colors.downloads.start.fg = '#1e1e1e'
c.colors.downloads.stop.bg = '#64ed02'
c.colors.downloads.stop.fg = '#1e1e1e'
c.colors.hints.bg = '#dddddd'
c.colors.hints.fg = '#101010'
c.colors.statusbar.caret.bg = '#7208d6'
c.colors.statusbar.caret.fg = '#1e1e1e'
c.colors.statusbar.caret.selection.bg = '#7208d6'
c.colors.statusbar.caret.selection.fg = '#1e1e1e'
c.colors.statusbar.insert.bg = '#222222'
c.colors.statusbar.insert.fg = '#64ed02'
c.colors.statusbar.url.success.http.fg = '#64ed02'
c.colors.statusbar.url.success.https.fg = '#64ed02'
c.colors.statusbar.url.warn.fg = '#dd2c04'
c.colors.tabs.even.bg = '#777777'
c.colors.tabs.even.fg = '#1e1e1e'
c.colors.tabs.odd.bg = '#777777'
c.colors.tabs.odd.fg = '#1e1e1e'
c.colors.tabs.indicator.error = '#dd2c04'
c.colors.tabs.indicator.start = '#dda304'
c.colors.tabs.indicator.stop = '#64ed02'
c.content.autoplay = False
c.content.blocking.enabled = True
c.content.blocking.method = "both"
c.content.javascript.enabled = True
c.content.notifications.enabled =False
c.hints.border = '1px solid #000000'
c.session.lazy_restore = True
c.tabs.indicator.width = 5
c.tabs.title.format = '{audio}{current_title}'
c.zoom.default = 75
c.fonts.default_family = "Iosevka"
c.fonts.default_size = "12px"
c.downloads.position = "bottom"
